Lumeos/server

- app.js
> added error handling for no users in db

- app.js
fixes #12 
I was debating between this and /v1/users/user_id/polls. I guess for now this works.
> Added queryCreator

- LICENSE.txt
- app.js
> Added check for used_id when answering poll and LICENSE

- app.js
> Added check when polls are empty

- app.js
> Added end point to upload profile picture

- app.js
> Added price increment for poll

- app.js
> Added queryTag fixes #9

- README.md
- app.js
- package-lock.json
- package.json
> Add login support with JWT

- app.js
> Added answer choice check

- app.js
> Convulated way to search polls by participant

- app.js
> Fixes issue where user can vote twice. No bueno

- app.js
> Add createdAt timestamp for polls

- app.js
- package-lock.json
- package.json
@zokir please see updates to handle OPTIONS requests and Cross origin requests
> Adds handling of OPTIONS requests and Cross origin requests

- app.js
> Added poll bying logic

- app.js
Adds User id to response object when searching for user by a query Param
> Adds user_id to response object when searching by user

- app.js
Just fix some code nits and reformat code.
> Reformat code

- package.json
- server.js
> Add persistent db

- server.js
- tests/data/simple_test.postman_collection.json
> Add eos and username fields

- package.json
- server.js
- tests/data/input_validation.postman_collection.json
- tests/data/simple_test.postman_collection.json
- tests/runner.js
> Validation

- package.json
- server.js
> Added contactus

- user_routes.js
> Added isFollowerOf and isFolloweeOf one to one end point

- user_routes.js
> Added image and user_id to followers

- user_routes.js
> Added unfollow
